name: Java CI

#on:
  #push:
    #branches: [ "master", "update" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      
      - name: Create Package
        env:
          VERSION: mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
        run: |
          echo $VERSION
          mkdir staging && mkdir staging/data
          cp -R config staging/
          cp data/setdata staging/data/
          cp -R data/icons staging/data/
          cp build/CardCollectionManager*.jar staging
          
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: Card-Collection-Manager-${VERSION}
          path: staging
          
