name: Java Snapshot CI

# on:
#   push:
#     branches: [ "*", "!master" ]
#   pull_request:
#     branches: [ "*", "!master" ]
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
      - uses: actions/checkout@v3
      
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Analyze Project Metadata
        run: |
          echo "PROJECT_GROUPID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
          echo "PROJECT_ARTIFACTID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      
      - name: Create Package
        run: |
          echo ${{ env.PROJECT_VERSION }}
          mkdir staging && mkdir staging/data
          cp -R config staging/
          cp data/setdata staging/data/
          cp -R data/icons staging/data/
          cp build/CardCollectionManager*.jar staging
          
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: Card-Collection-Manager-${{ env.PROJECT_VERSION }}
          path: staging
          
